
export const jobs = [
  {
    id: "1",
    title: "MATA Group",
    logo: "./img/logo_1.webp",
    job: "Trợ Lý",
    address: "609 Truong Dinh - Hoang Mai - Ha Noi",
    requirements: ["Fulltime", "Kinh nghiệm 2 năm" , "Thực tập" ], 
    luong: "$500 USD",
  },
    {
        id: "2",
        title: "PT Mandala Karya Prima",
        logo: "./img/logo_2.webp",
        job: "SEO Leader",
        address: "609 Truong Dinh - Hoang Mai - Ha Noi",
        requirements: ["Fulltime", "Thực tập", "Parttime"], 
        luong: "$500 USD",
      },
      {
        id: "3",
        title: "Alex Villas Furniture",
        logo: "./img/logo_3.webp",
        job: "Kế toán",
        address: "609 Truong Dinh - Hoang Mai - Ha Noi",
        requirements: ["Fulltime", "Kinh nghiệm 2 năm"],
        luong: "$500 USD",
      },
      {
        id: "1",
        title: "MATA Group",
        logo: "./img/logo_1.webp",
        job: "Trợ Lý",
        address: "609 Truong Dinh - Hoang Mai - Ha Noi",
        requirements: ["Fulltime", "Kinh nghiệm 2 năm"],
        luong: "$500 USD - $650 USD",
      },
      {
          id: "2",
          title: "PT Mandala Karya Prima",
          logo: "./img/logo_2.webp",
          job: "SEO Leader",
          address: "609 Truong Dinh - Hoang Mai - Ha Noi",
          requirements: ["Fulltime", "Kinh nghiệm 2 năm"], 
          luong: "$500 USD",
        },
        {
          id: "3",
          title: "Alex Villas Furniture",
          logo: "./img/logo_3.webp",
          job: "Kế toán",
          address: "609 Truong Dinh - Hoang Mai - Ha Noi",
          requirements: ["Fulltime", "Kinh nghiệm 2 năm"], 
          luong: "$500 USD",
        },
  ];
  