// companyData.ts
export const companies = [
  {
    id: "1",
    title: "MATA Group - Công ty TNHH Thương mại và dịch vụ công nghệ Mata",
    logo: "../img/logo_1.webp",
    nation: "Ha Noi - Viet Nam",
    address: "609 Truong Dinh - Hoang Mai - Ha Noi",
    industry: "Technology information",
    info: "https://chat.openai.com",
    size: "30 - 50 ",
  },
  {
    id: "2",
    title: "PT Mandala Karya Prima",
    logo: "./img/logo_1.webp",
    nation: "Ho Chi Minh - Viet Nam",
    address: "17 Kieu Mai - Phu Dien - Tp.Ho Chi Minh",
    industry: "Mining & Metals",
    info: "https://chat.openai.com/c/1e78142f-cf4e-4e33-a9eb-b8c26bc07301",
    size: "30",
  },
  {
    id: "3",
    title: "Alex Villas Furniture",
    logo: "./img/logo_1.webp",
    nation: "Hai Duong - Viet Nam",
    address: "101 Truong Trinh - Tan Binh - Hai Duong",
    industry: "Media Production",
    info: "https://chat.openai.com",
    size: "30",
  },
  {
    id: "4",
    title: "MATA Group",
    logo: "./img/logo_1.webp",
    nation: "Ha Noi - Viet Nam",
    address: "609 Truong Dinh - Hoang Mai - Ha Noi",
    industry: "Technology information",
    info: "https://chat.openai.com/c/1e78142f-cf4e-4e33-a9eb-b8c26bc07301",
    size: "30",
  },
  {
    id: "5",
    title: "PT Mandala Karya Prima",
    logo: "./img/logo_1.webp",
    nation: "Ho Chi Minh - Viet Nam",
    address: "17 Kieu Mai - Phu Dien - Tp.Ho Chi Minh",
    industry: "Mining & Metals",
    info: "https://chat.openai.com/c/1e78142f-cf4e-4e33-a9eb-b8c26bc07301",
    size: "30",
  },
  {
    id: "6",
    title: "Alex Villas Furniture",
    logo: "./img/logo_1.webp",
    nation: "Hai Duong - Viet Nam",
    address: "101 Truong Trinh - Tan Binh - Hai Duong",
    industry: "Media Production",
    info: "https://chat.openai.com/c/1e78142f-cf4e-4e33-a9eb-b8c26bc07301",
    size: "30",
  },
];
