// companyData.ts
export const companies = [
  {
    id: "1",
    title: "MATA Group",
    logo: "./img/logo_1.webp",
    nation: "Ha Noi - Viet Nam",
    address: "609 Truong Dinh - Hoang Mai - Ha Noi",
    industry: "Technology information",
    info: "Bùi Đư",
  },
  {
    id: "2",
    title: "PT Mandala Karya Prima",
    logo: "./img/logo_2.webp",
    nation: "Ho Chi Minh - Viet Nam",
    address: "17 Kieu Mai - Phu Dien - Tp.Ho Chi Minh",
    industry: "Mining & Metals",
    info: "",
  },
  {
    id: "3",
    title: "Alex Villas Furniture",
    logo: "./img/logo_3.webp",
    nation: "Hai Duong - Viet Nam",
    address: "101 Truong Trinh - Tan Binh - Hai Duong",
    industry: "Media Production",
    info: "",
  },
  {
    id: "4",
    title: "MATA Group",
    logo: "./img/logo_1.webp",
    nation: "Ha Noi - Viet Nam",
    address: "609 Truong Dinh - Hoang Mai - Ha Noi",
    industry: "Technology information",
    info: "",
  },
  {
    id: "5",
    title: "PT Mandala Karya Prima",
    logo: "./img/logo_2.webp",
    nation: "Ho Chi Minh - Viet Nam",
    address: "17 Kieu Mai - Phu Dien - Tp.Ho Chi Minh",
    industry: "Mining & Metals",
    info: "",
  },
  {
    id: "6",
    title: "Alex Villas Furniture",
    logo: "./img/logo_3.webp",
    nation: "Hai Duong - Viet Nam",
    address: "101 Truong Trinh - Tan Binh - Hai Duong",
    industry: "Media Production",
    info: "",
  },
];
